# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rg', models.IntegerField(max_length=12)),
                ('cpf', models.IntegerField(max_length=11)),
                ('estadocivil', models.CharField(max_length=20)),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Sexo'),
        ),
    ]
