# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_my_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(help_text='Escreva aqui somente os numeros do CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(help_text='Escreva aqui o seu e-mail', max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(help_text='Escreva aqui nome completo do sua mae', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Escreva aqui o seu nome completo', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(help_text='Escreva aqui nome completo do seu pai', max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.IntegerField(help_text='Escreva aqui somente os numeros do RG'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Escreva aqui o numero de seu telefone (xx) 99999-9999', max_length=15),
        ),
    ]
