# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_myproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(help_text='Escreva aqui somente os numeros do CPF', unique=True, verbose_name='Numero do CPF:'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(help_text='Escreva aqui o seu e-mail', max_length=200, validators=['validate_email']),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.IntegerField(help_text='Escreva aqui somente os numeros do RG', unique=True, verbose_name='Numero do RG:'),
        ),
    ]
