# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_myproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0, help_text='Coloque aqui sua idade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(help_text='Escreva aqui o seu e-mail', max_length=200),
        ),
    ]
