# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0008_my_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(error_messages={'null': 'Valor nulo nao permitido'}, help_text='Escreva aqui o seu nome completo', max_length=100, verbose_name='Nome Completo:'),
        ),
    ]
