# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_my_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estadocivil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado')], default='S', error_messages={'invalid_choice': 'Valor nao permitido'}, max_length=20),
        ),
    ]
