# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0013_my_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome', '-idade'], 'verbose_name': ['Pessoa', 'Pessoas']},
        ),
    ]
