# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import pessoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_my_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0, help_text='Coloque aqui sua idade', validators=[pessoa.models.validate_even]),
        ),
    ]
