# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import pessoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0017_auto_20200212_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.IntegerField(db_index=True, help_text='Escreva aqui somente os numeros do CPF', unique=True, verbose_name='N\xfamero do CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dt_log',
            field=models.DateField(auto_now=True, verbose_name='Dt Cria\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(help_text='Escreva aqui o seu e-mail', max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estadocivil',
            field=models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('V', 'Vi\xfavo'), ('D', 'Desquitado'), ('U', 'Uni\xe3o Est\xe1vel')], db_index=True, default='S', error_messages={'invalid_choice': 'Valor nao permitido'}, max_length=20, verbose_name='Estado C\xedvil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0, help_text='Coloque aqui sua idade', validators=[pessoa.models.validate_even], verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(help_text='Escreva aqui nome completo do sua mae', max_length=100, verbose_name='Nome da M\xe3e'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(error_messages={'blank': 'Valor vazio', 'null': 'Valor nulo nao permitido'}, help_text='Escreva aqui o seu nome completo', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(help_text='Escreva aqui nome completo do seu pai', max_length=100, verbose_name='Nome do Pai'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='rg',
            field=models.IntegerField(help_text='Escreva aqui somente os numeros do RG', unique=True, verbose_name='N\xfamero do RG'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(help_text='Escreva aqui o numero de seu telefone (xx) 99999-9999', max_length=15, verbose_name='Telefone'),
        ),
    ]
