# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0020_auto_20200213_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(db_index=True, help_text='Escreva aqui somente os numeros do CPF', max_length=15, unique=True, verbose_name='N\xfamero do CPF'),
        ),
    ]
