# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0021_auto_20200217_0826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sexo',
            new_name='Genero',
        ),
    ]
