# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0023_auto_20200218_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, default='pessoa_fotos/none.jpg', help_text='Escolha uma foto para o seu perfil', upload_to='pessoa_fotos/', verbose_name='Foto'),
        ),
    ]
