# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0026_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to='pessoa_fotos/')),
                ('upload_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
