# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0028_auto_20200306_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='pessoa_fotos/'),
        ),
    ]
