# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0029_auto_20200306_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pub_date', 'question'], 'permissions': (('list_poll', 'Listagem Poll'),), 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
    ]
