# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0030_auto_20200309_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome', 'idade'], 'permissions': (('list_pessoa', 'Listagem de Pessoa'),), 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-pub_date', 'question'], 'permissions': (('list_poll', 'Listagem de Poll'),), 'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(blank=True, help_text='Escreva aqui o seu e-mail, lista de e-mails separado por ;', max_length=200, null=True, verbose_name='E-Mail'),
        ),
    ]
